builders:
  yaru_color_builder:
    import: "package:yaru_color_builder/yaru_color_builder.dart"
    builder_factories: ["yaruColorBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen"]
